export const skills = [
	"Arch",
	"Bite",
	"Climb",
	"Focus",
	"Hiss",
	"Jump",
	"Listen",
	"Ponder",
	"Pounce",
	"See",
	"Smell",
	"Sneak",
	"Swat",
	"Swim",
	"Wrestle",
];

export const skillData = {
	0: 0,
	1: 0,
	2: 0,
	3: 2,
	4: 2,
	5: 2,
	6: 2,
	7: 1,
	8: 1,
	9: 1,
	10: 1,
	11: 2,
	12: 1,
	13: 0,
	14: 0,
};

export const knacks = [
	"Alertness (1 SPT chip = +1 to Listen, See, Scent, Focus, or Ponder)",
	"Animal Lore (1 INT chip = +1 to Intelligence or Ponder involving animals)",
	"Balance (1 SPT chip = +1 to Climb or Strength)",
	"Belly Rake (2 STR chip = Belly Rake attack, Swat but +1 damage)",
	"Chomp (3 STR chip = Chomp attack, Pins enemy)",
	"Clan Lore (1 INT chip = +1 to Intelligence or Ponder)",
	"Dash (1 STR chip = Move quickly)",
	"Dodge (1 SPT chip = +1 to Jump)",
	"Feint (1 INT chip = +1 to Swat, improves chances but doesn't add damage)",
	"Herb Lore (1 INT chip = +1 to Intelligence or Ponder involving herbs)",
	"Hide (1 SPT chip = +2 to Sneak)",
	"Interpret Dreams (2 SPT chip = Understand dreams)",
	"Launch (3 STR chip = Launch attack, needs you and enemy be wrestling)",
	"Leap (1 STR chip = Pounce further)",
	"Medicine Lore (1 INT chip = +1 to Intelligence or Ponder involving knows what a is ailing a sick cat)",
	"Mighty Swat (1 STR chip = +1 attack damage to Swat)",
	"Orate (1 SPT chip = +1 to Spirit, Focus, or Ponder)",
	"Pathfinder (1 INT chip = Know distance to known place and known places near you)",
	"Pin (3 STR chip = Pin attack, make enemy not able to move)",
	"Pummel (3 STR chip = Make Swat use a strength check instead of intelligence)",
	"Spring (3 STR chip = Go to a high object)",
	"Stalk (1 SPT chip = +2 to Sneak)",
	"Track (1 INT chip = +1 to Listen, See or Smell)",
	"Twoleg Lore (1 INT chip = +1 to Intelligence or Ponder involving Twolegs",
	"Yowl (1 INT = +1 to Arch or Hiss)",
];

export const knackData = [
	{
		name: "Alertness",
		spentOn: [3, 6, 7, 9, 10],
		cost: 1,
		costType: 2,
		category: "all",
		max: 0,
		upgrade: 2,
		upgradeReward: "bonusIncrease",
	},
	{
		name: "Animal Lore",
		spentOn: [7],
		spentAbil: [1],
		cost: 1,
		costType: 1,
		category: "animal",
		upgrade: -1,
		upgradeReward: "bonusIncrease",
	},
	{
		name: "Balance",
		spentOn: [2],
		spentAbil: [0],
		cost: 1,
		costType: 2,
		category: "ledge",
		max: 0,
		upgrade: 1,
	},
	{
		name: "Belly Rake",
		cost: 2,
		costType: 0,
		category: "attack",
		upgrade: 2,
		upgradeReward: "cost",
	},
	{
		name: "Chomp",
		attack: true,
		cost: 3,
		costType: 0,
		category: "attack",
		upgrade: 1,
	},
	{
		name: "Clan Lore",
		spentOn: [7],
		spentAbil: [1],
		cost: 1,
		costType: 1,
		category: "clan",
		upgrade: -1,
		upgradeReward: "bonusIncrease",
	},
	{
		name: "Dash",
		cost: 1,
		costType: 0,
		category: "check",
		upgrade: 1,
	},
	{
		name: "Dodge",
		spentOn: [5],
		cost: 1,
		costType: 2,
		category: "all",
		upgrade: 3,
		upgradeReward: "bonusIncrease",
	},
	{
		name: "Feint",
		cost: 1,
		costType: 1,
		category: "attack",
		upgrade: 3,
		upgradeReward: "bonusIncrease",
	},
	{
		name: "Herb Lore",
		spentOn: [7],
		spentAbil: [1],
		cost: 1,
		costType: 1,
		category: "herb",
		upgrade: -1,
		upgradeReward: "bonusIncrease",
	},
	{
		name: "Hide",
		spentOn: [11],
		cost: 1,
		costType: 2,
		adds: 2,
		category: "hide",
		max: 0,
		upgrade: 1,
	},
	{
		name: "Interpret Dreams",
		cost: 2,
		costType: 2,
		category: "check",
		upgrade: 2,
		upgradeReward: "cost",
	},
	{
		name: "Launch",
		cost: 3,
		costType: 0,
		category: "attack",
		max: 4,
		upgrade: 2,
		upgradeReward: "cost",
	},
	{
		name: "Leap",
		cost: 1,
		costType: 2,
		category: "check",
		max: 4,
		upgrade: 1,
	},
	{
		name: "Medicine Lore",
		spentOn: [7],
		spentAbil: [1],
		cost: 1,
		costType: 1,
		category: "medicine",
		upgrade: -1,
		upgradeReward: "bonusIncrease",
	},
	{
		name: "Mighty Swat",
		cost: 2,
		costType: 0,
		category: "attack",
		max: 0,
		upgrade: 2,
		upgradeReward: "cost",
	},
	{
		name: "Orate",
		spentOn: [3, 7],
		spentAbil: [2],
		cost: 1,
		costType: 2,
		category: "orate",
		upgrade: -1,
		upgradeReward: "bonusIncrease",
	},
	{
		name: "Pathfinder",
		cost: 1,
		costType: 1,
		category: "check",
		upgrade: 2,
		upgradeReward: "check",
	},
	{
		name: "Pin",
		cost: 3,
		costType: 0,
		category: "attack",
		upgrade: 2,
		upgradeReward: "cost",
	},
	{
		name: "Pummel",
		cost: 3,
		costType: 0,
		category: "attack",
		upgrade: 2,
		upgradeReward: "cost",
	},
	{
		name: "Spring",
		cost: 3,
		costType: 0,
		category: "check",
		upgrade: 3,
		upgradeReward: "cost",
	},
	{
		name: "Stalk",
		spentOn: [11],
		cost: 1,
		costType: 2,
		adds: 2,
		category: "stalk",
		max: 0,
		upgrade: 1,
	},
	{
		name: "Track",
		spentOn: [6, 9, 10],
		cost: 1,
		costType: 1,
		category: "track",
		max: 0,
		upgrade: 2,
		upgradeReward: "bonusIncrease",
	},
	{
		name: "Twoleg Lore",
		spentOn: [7],
		spentAbil: [1],
		cost: 1,
		costType: 1,
		category: "twoleg",
		upgrade: -1,
		upgradeReward: "bonusIncrease",
	},
	{
		name: "Yowl",
		spentOn: [0, 4],
		cost: 1,
		costType: 1,
		category: "all",
		upgrade: 3,
		upgradeReward: "bonusIncrease",
	},
];

export const age = {
	11: "skill",
	12: "ability",
	13: "knack",
	14: "intSpt",
	15: "skill",
	16: "knack",
	17: "ability",
	19: "skillKnack",
	21: "ability",
	22: "knack",
	23: "skill",
	25: "knack",
	26: "intSpt",
	27: "skill",
	28: "knack",
	31: "skillKnack",
	32: "ability",
	34: "knack",
	35: "skill",
	37: "knack",
	38: "int",
	39: "skill",
	40: "knack",
	43: "knackSkill",
	45: "ability",
	46: "knack",
	47: "skill",
	49: "knack",
	50: "spt",
	51: "skill",
	52: "knack",
	55: "knackSkill",
	57: "weaken",
	58: "knack",
	59: "skill",
	61: "knack",
	62: "ability",
	63: "skill",
	64: "knack",
	67: "knackSkill",
	68: "weaken",
	69: "spt",
	70: "knack",
};
